[project]
name = "pdr-cleanup"
version = "0.1.0"
description = "This task is for cleaning up PDRs after a successful ingest"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cumulus-message-adapter-python==2.4",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
