version: '3'
services:
  local:
    image: cumuluss/circleci:node-8.11
    command: start
    volumes:
      - "./packages/test-data:/home/vsftpd:ro"
      - "./packages/test-data:/var/www/html:ro"
      - "./packages/test-data:/home/user"
      - "./packages/test-data/keys:/home/user/.ssh"
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
      - "3030:3030"
      - "2222:2222"
    links:
      - localstack
      - locales
    depends_on:
      - localstack
      - locales

  test:
    image: cumuluss/circleci:node-8.11
    command: /bin/bash
    volumes:
      - ".:/home/circleci/project"
      - "./packages/test-data:/home/vsftpd:ro"
      - "./packages/test-data:/var/html:ro"
      - "./packages/test-data:/home/user"
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
      - "3030:3030"
      - "2222:2222"
    links:
      - localstack
      - locales
    depends_on:
      - localstack
      - locales

  localstack:
    image: localstack/localstack:0.8.7
    environment:
      SERVICES: 'kinesis,dynamodb,dynamodbstreams,lambda,s3,sns,sqs'
    ports:
      # skipping 4571 that belongs to elasticsearch
      - 4567-4570:4567-4570
      - 4572-4582:4572-4582
      - 8080:8080

  locales:
    image: elasticsearch:5.6
    environment:
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
    ports:
      - 4571:9200
