version: '3'
services:
  ftp:
    image: cumuluss/vsftpd:2
    ports:
      - "127.0.0.1:21:21"
      - "127.0.0.1:4559-4564:4559-4564"
    volumes:
      - ../packages/test-data:/srv:ro
    environment:
      - FTP_USER=testuser
      - FTP_PASSWORD=testpass
      - FTP_PASV_ADDRESS=127.0.0.1
  http:
    image: httpd:alpine
    ports:
      - "127.0.0.1:3030:80"
    volumes:
      - ../packages/test-data:/usr/local/apache2/htdocs:ro
  sftp:
    # image: panubo/sshd
    image: nsidc/panubo_sshd:latest
    command: /bootstrap-sftp.sh
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - ./bootstrap-sftp.sh:/bootstrap-sftp.sh
      - ../packages/test-data/keys/ssh_client_rsa_key.pub:/etc/authorized_keys/user
      - ../packages/test-data:/data
    environment:
      - SSH_USERS=user:2000:2000
      - SFTP_MODE=true
  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
  localstack:
    image: localstack/localstack:0.8.7
    ports:
      - "127.0.0.1:4568:4568"
      - "127.0.0.1:4569:4569"
      - "127.0.0.1:4570:4570"
      - "127.0.0.1:4571:4571"
      - "127.0.0.1:4572:4572"
      - "127.0.0.1:4574:4574"
      - "127.0.0.1:4575:4575"
      - "127.0.0.1:4576:4576"
    environment:
      SERVICES: 'kinesis,lambda,s3,sns,sqs,dynamodb,dynamodbstreams'
