stackName: test-npm-integration
bucket: cumulus-test-sandbox-internal
DiscoverAndQueuePdrs: &defaults
  meta:
    stack: test-npm-integration
    buckets:
      internal: cumulus-test-sandbox-internal
      private: cumulus-test-sandbox-private
    templates:
      ParsePdr: s3://cumulus-test-sandbox-internal/test-npm-integration/workflows/ParsePdr.json
      IngestGranule: s3://cumulus-test-sandbox-internal/test-npm-integration/workflows/IngestGranule.json
    queues:
      startSF: https://sqs.us-east-1.amazonaws.com/{{AWS_ACCOUNT_ID}}/test-npm-integration-startSF
ParsePdr: *defaults
IngestGranule:
  <<: *defaults
  SyncGranuleOutput:
    granules:
      - files:
        - bucket: cumulus-test-sandbox-private
          filename: s3://cumulus-test-sandbox-private/MOD09GQ.A2016358.h13v04.006.2016360104606.hdf
        - bucket: cumulus-test-sandbox-private
          filename: s3://cumulus-test-sandbox-private/MOD09GQ.A2016358.h13v04.006.2016360104606.hdf.met
