ApiCollectionsV1:
  handler: index.collections
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    CollectionsTable:
      function: Ref
      value: CollectionsTableDynamoDB
    internal: '{{parent.system_bucket}}'
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    # v1 paths
    - path: v1/collections
      method: get
      cors: true
      api: backend
    - path: v1/collections
      method: post
      cors: true
      api: backend
    - path: v1/collections/{collectionName}/{version}
      method: get
      cors: true
      api: backend
    - path: v1/collections/{collectionName}/{version}
      method: put
      cors: true
      api: backend
    - path: v1/collections/{collectionName}/{version}
      method: delete
      cors: true
      api: backend

ApiGranulesV1:
  handler: index.granules
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/'
  apiRole: true
  urs: true
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    CollectionsTable:
      function: Ref
      value: CollectionsTableDynamoDB
    ProvidersTable:
      function: Ref
      value: ProvidersTableDynamoDB
    GranulesTable:
      function: Ref
      value: GranulesTableDynamoDB
    invoke:
      function: "Ref"
      value: ScheduleSFLambdaFunction
    bucket: '{{parent.system_bucket}}'
    internal: '{{parent.system_bucket}}'
    cmr_provider: '{{parent.cmr.provider}}'
    cmr_client_id: '{{parent.cmr.clientId}}'
    cmr_username: '{{parent.cmr.username}}'
    cmr_password:
      function: "Ref"
      value: "CmrPassword"
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    # v1 paths
    - path: v1/granules
      method: get
      cors: true
      api: backend
    - path: v1/granules/{granuleName}
      method: get
      cors: true
      api: backend
    - path: v1/granules/{granuleName}
      method: put
      cors: true
      api: backend
    - path: v1/granules/{granuleName}
      method: delete
      cors: true
      api: backend

ApiExecutionsV1:
  handler: index.executions
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
    ExecutionsTable:
      function: Ref
      value: ExecutionsTableDynamoDB
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    #v1 paths
    - path: v1/executions
      method: get
      cors: true
      api: backend
    - path: v1/executions/{arn}
      method: get
      cors: true
      api: backend

ApiExecutionStatusV1:
  handler: index.executionStatus
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    #v1 paths
    - path: v1/executions/status/{arn}
      method: get
      cors: true
      api: backend

ApiWorkflowsV1:
  handler: index.workflows
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    bucket: '{{parent.system_bucket}}'
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    #v1 paths
    - path: v1/workflows
      method: get
      cors: true
      api: backend
    - path: v1/workflows/{name}
      method: get
      cors: true
      api: backend

ApiRulesV1:
  handler: index.rules
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  envs:
    bucket: '{{parent.system_bucket}}'
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    CollectionsTable:
      function: Ref
      value: CollectionsTableDynamoDB
    ProvidersTable:
      function: Ref
      value: ProvidersTableDynamoDB
    RulesTable:
      function: Ref
      value: RulesTableDynamoDB
    invoke:
      function: "Ref"
      value: ScheduleSFLambdaFunction
    invokeArn:
      function: "Ref"
      value: ScheduleSFLambdaFunction
    messageConsumer:
      function: "Ref"
      value: messageConsumerLambdaFunction
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  source: 'node_modules/@cumulus/api/dist/'
  apiGateway:
    #v1 paths
    - path: v1/rules
      method: get
      cors: true
      api: backend
    - path: v1/rules/{name}
      method: get
      cors: true
      api: backend
    - path: v1/rules
      method: post
      cors: true
      api: backend
    - path: v1/rules/{name}
      method: put
      cors: true
      api: backend
    - path: v1/rules/{name}
      method: delete
      cors: true
      api: backend

ApiProvidersV1:
  handler: index.providers
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    ProvidersTable:
      function: Ref
      value: ProvidersTableDynamoDB
    internal: '{{parent.system_bucket}}'
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  source: 'node_modules/@cumulus/api/dist/'
  apiGateway:
    #v1 paths
    - path: v1/providers
      method: get
      cors: true
      api: backend
    - path: v1/providers/{id}
      method: get
      cors: true
      api: backend
    - path: v1/providers
      method: post
      cors: true
      api: backend
    - path: v1/providers/{id}
      method: put
      cors: true
      api: backend
    - path: v1/providers/{id}
      method: delete
      cors: true
      api: backend

ApiPdrsV1:
  handler: index.pdrs
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    internal: '{{parent.system_bucket}}'
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
    PdrsTable:
      function: Ref
      value: PdrsTableDynamoDB
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    #v1 paths
    - path: v1/pdrs
      method: get
      cors: true
      api: backend
    - path: v1/pdrs/{pdrName}
      method: get
      cors: true
      api: backend
    - path: v1/pdrs/{pdrName}
      method: delete
      cors: true
      api: backend

ApiLogsV1:
  handler: index.logs
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/'
  apiRole: true
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    #v1 paths
    - path: v1/stats/logs
      method: get
      cors: true
      api: backend
    - path: v1/logs
      method: get
      cors: true
      api: backend
    - path: v1/logs/{executionName}
      method: get
      cors: true
      api: backend

ApiSchemaV1:
  handler: index.schemas
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    #v1 paths
    - path: v1/schemas/{schemaName}
      method: get
      cors: true
      api: backend

ApiStatsV1:
  handler: index.stats
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/'
  apiRole: true
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    #v1 paths
    - path: v1/stats
      method: get
      cors: true
      api: backend
    - path: v1/stats/histogram
      method: get
      cors: true
      api: backend
    - path: v1/stats/aggregate
      method: get
      cors: true
      api: backend
    - path: v1/stats/average
      method: get
      cors: true
      api: backend

ApiTokenV1:
  handler: index.token
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/'
  apiRole: true
  urs: true
  envs:
    EARTHDATA_BASE_URL: '{{parent.urs_url}}'
    EARTHDATA_CLIENT_ID: '{{EARTHDATA_CLIENT_ID}}'
    EARTHDATA_CLIENT_PASSWORD: '{{EARTHDATA_CLIENT_PASSWORD}}'
    AccessTokensTable:
      function: Ref
      value: AccessTokensTableDynamoDB
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    OAUTH_PROVIDER: '{{parent.oauth.provider}}'
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    #v1 paths
    - api: backend
      path: v1/token
      method: get
      cors: true
    - api: backend
      path: v1/refresh
      method: post
      cors: true
    - api: backend
      path: v1/tokenDelete/{jwtToken}
      method: delete
      cors: true

ApiVersionV1:
  handler: index.version
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/'
  apiGateway:
    #v1 paths
    - api: backend
      path: v1/version
      method: get
      cors: true

ApiReconciliationReportV1:
  handler: index.reconciliationReports
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    system_bucket: '{{parent.system_bucket}}'
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    invoke:
      function: Ref
      value: CreateReconciliationReportLambdaFunction
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    #default paths
    - path: v1/reconciliationReports
      method: get
      cors: true
      api: backend
    - path: v1/reconciliationReports/{name}
      method: get
      cors: true
      api: backend
    - path: v1/reconciliationReports
      method: post
      cors: true
      api: backend
    - path: v1/reconciliationReports/{name}
      method: delete
      cors: true
      api: backend

ApiAsyncOperationsV1:
  handler: index.asyncOperations
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    stackName: '{{parent.stackName}}'
    systemBucket: '{{parent.bucket}}'
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    AsyncOperationsTable:
      function: Ref
      value: AsyncOperationsTableDynamoDB
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    - api: backend
      path: v1/asyncOperations/{id}
      method: get
      cors: true

ApiBulkDeleteV1:
  handler: index.bulkDeleteEndpoint
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  apiGateway:
    - api: backend
      path: v1/bulkDelete
      method: post
      cors: true
  envs:
    EcsCluster:
      function: Ref
      value: EcsCluster
    AsyncOperationsTable:
      function: Ref
      value: AsyncOperationsTableDynamoDB
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    BulkDeleteLambda:
      function: Ref
      value: BulkDeleteLambdaFunction
    AsyncOperationTaskDefinition:
      function: Ref
      value: AsyncOperationTaskDefinition
    stackName: '{{parent.stackName}}'
    systemBucket: '{{parent.bucket}}'
    TOKEN_SECRET: '{{TOKEN_SECRET}}'

ApiInstanceMetaV1:
  handler: index.instanceMeta
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    cmr_provider: '{{parent.cmr.provider}}'
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    # Default paths
    - api: backend
      path: v1/instanceMeta
      method: get
      cors: true
