ApiEndpoints:
  handler: index.handler
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/app/'
  apiRole: true
  urs_redirect: 'token'
  useDistributionApi: true
  addLogGroup: true
  useElasticSearch: '{{parent.es.name}}'
  launchInVpc: true
  envs:
    EARTHDATA_BASE_URL: '{{parent.urs_url}}'
    EARTHDATA_CLIENT_ID: '{{EARTHDATA_CLIENT_ID}}'
    EARTHDATA_CLIENT_PASSWORD: '{{EARTHDATA_CLIENT_PASSWORD}}'
    OAUTH_PROVIDER: '{{parent.oauth.provider}}'
    AccessTokensTable:
      function: Ref
      value: AccessTokensTableDynamoDB
    AsyncOperationsTable:
      function: Ref
      value: AsyncOperationsTableDynamoDB
    CollectionsTable:
      function: Ref
      value: CollectionsTableDynamoDB
    ExecutionsTable:
      function: Ref
      value: ExecutionsTableDynamoDB
    GranulesTable:
      function: Ref
      value: GranulesTableDynamoDB
    PdrsTable:
      function: Ref
      value: PdrsTableDynamoDB
    ProvidersTable:
      function: Ref
      value: ProvidersTableDynamoDB
    RulesTable:
      function: Ref
      value: RulesTableDynamoDB
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    AsyncOperationTaskDefinition:
      function: Ref
      value: AsyncOperationTaskDefinition
    EcsCluster:
      function: Ref
      value: EcsCluster
    system_bucket: '{{parent.system_bucket}}'
    BulkDeleteLambda:
      function: Ref
      value: BulkDeleteLambdaFunctionArn
    invoke:
      function: Ref
      value: ScheduleSFLambdaFunctionArn
    invokeArn:
      function: Ref
      value: ScheduleSFLambdaFunctionArn
    invokeReconcileLambda:
      function: Ref
      value: CreateReconciliationReportLambdaFunctionArn
    messageConsumer:
      function: Ref
      value: messageConsumerLambdaFunctionArn
    KinesisInboundEventLogger:
      function: Ref
      value: KinesisInboundEventLoggerLambdaFunctionArn
    STSCredentialsLambda: '{{parent.sts_credentials_lambda}}'
    cmr_provider: '{{parent.cmr.provider}}'
    cmr_client_id: '{{parent.cmr.clientId}}'
    cmr_username: '{{parent.cmr.username}}'
    cmr_password:
      function: "Ref"
      value: "CmrPassword"
    TOKEN_SECRET: '{{TOKEN_SECRET}}'
  apiGateway:
    - api: backend
      path: '{proxy+}'
      method: any
