
ApiDistribution:
  handler: index.distributionAppHandler
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/'
  distributionRole: true
  urs: true
  envs:
    EARTHDATA_BASE_URL: '{{parent.urs_url}}'
    EARTHDATA_CLIENT_ID: '{{EARTHDATA_CLIENT_ID}}'
    EARTHDATA_CLIENT_PASSWORD: '{{EARTHDATA_CLIENT_PASSWORD}}'
    AccessTokensTable:
      function: Ref
      value: AccessTokensTableDynamoDB
  apiGateway:
    - api: distribution
      path: 'redirect'
      method: get
    - api: distribution
      path: '{proxy+}'
      method: any
