[project]
name = "granule-invalidator"
version = "0.1.0"
description = "Identifies granules that fulfill specific criteria"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cumulus-api",
    "cumulus-message-adapter>=2.0.5",
    "cumulus-message-adapter-python>=2.4.0",
]

[project.urls]
homepage = "https://github.com/nasa/cumulus/blob/master/tasks/granule-invalidator"
documentation = "https://github.com/nasa/cumulus/blob/master/tasks/granule-invalidator/README.md"
repository = "https://github.com/nasa/cumulus.git"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]

[tool.uv.sources]
cumulus-api = { git = "https://github.com/ghrcdaac/cumulus-api", tag = "v3.0.4" }
